os: linux
language: go
# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
# sudo: requried
dist: trusty

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on
    - REGISTRY_USER=${REGISTRY_USER}
    - REGISTRY_PASS=${REGISTRY_PASS}
    - secure: "${REGISTRY_SECURE}"
  jobs:
    - TARGET=amd64
    - TARGET=ppc64le

before_install:
  - sudo apt-get update -qq
  - go get github.com/mattn/goveralls

install:
  - go get -u golang.org/x/lint/golint

before_script:
  # Make gopath... to run golint/go fmt/go vet
  # Suppress golint for fixing lint later.
  - golint ./... | grep -v vendor | grep -v ALL_CAPS | xargs -r false
  - go fmt ./...
  - go vet ./...
#  - gocyclo -over 15 ./multus

script:
  - GOARCH="${TARGET}" ./build
  - |
    if [ "${TARGET}" == "amd64" ]; then
      sudo env PATH=${PATH} ./test.sh
      goveralls -coverprofile=coverage.out -service=travis-ci
      docker build -t nfvpe/multus:latest-amd64 .
      docker build -t nfvpe/multus:latest-ppc64le -f Dockerfile.ppc64le .
      docker build -t nfvpe/multus-origin:latest -f Dockerfile.openshift .
    fi

deploy:
  # Release on versioned tag (e.g. v1.0)
  - provider: script
    #cleanup: false
    script: curl -sL https://git.io/goreleaser
    on:
      tags: true
      all_branches: true
      condition: "$TARGET = amd64 && $TRAVIS_TAG =~ ^v[0-9].*$ && ! -z $GITHUB_TOKEN && $TRAVIS_OS_NAME = linux"
  # Push images to Dockerhub on tag
  - provider: script
    cleanup: false
    script: >
      bash -c '
      docker tag nfvpe/multus:latest-amd64 nfvpe/multus:latest;
      docker tag nfvpe/multus:latest-amd64 nfvpe/multus:stable;
      docker tag nfvpe/multus:latest-amd64 nfvpe/multus:stable-amd64;
      docker tag nfvpe/multus:latest-amd64 nfvpe/multus:$TRAVIS_TAG;
      docker tag nfvpe/multus:latest-ppc64le nfvpe/multus:stable-ppc64le;
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"; 
      docker push nfvpe/multus:latest;
      docker push nfvpe/multus:latest-amd64;
      docker push nfvpe/multus:latest-ppc64le;
      docker push nfvpe/multus:stable;
      docker push nfvpe/multus:stable-amd64;
      docker push nfvpe/multus:stable-ppc64le;
      docker push nfvpe/multus:$TRAVIS_TAG;
      echo done'
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$ && -n $REGISTRY_USER && -n $REGISTRY_PASS"
  # Push images to Dockerhub on merge to master
  - provider: script
    on:
      branch: master
      condition: "-n $REGISTRY_USER && -n $REGISTRY_PASS"
    script: >
      bash -c '
      docker tag nfvpe/multus:latest-amd64 nfvpe/multus:snapshot;
      docker tag nfvpe/multus:latest-amd64 nfvpe/multus:snapshot-amd64;
      docker tag nfvpe/multus:latest-ppc64le nfvpe/multus:snapshot-ppc64le;
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS";
      docker push nfvpe/multus:snapshot;
      docker push nfvpe/multus:snapshot-amd64;
      docker push nfvpe/multus:snapshot-ppc64le;
      docker push nfvpe/multus:latest;
      docker push nfvpe/multus:latest-amd64;
      docker push nfvpe/multus:latest-ppc64le;
      echo done'
