name: Docker-build-push-stable
on: 
  push:
    tags:
      - v*
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
      TARGET: amd64
      REPOSITORY: nfvpe/multus
      REPOSITORY_USER: nfvperobot
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
  
      - name: Build latest-amd64
        run: docker build -t ${REPOSITORY}:latest-amd64 -f deployments/Dockerfile .
  
      - name: Build latest-ppc64le
        run: docker build -t ${REPOSITORY}:latest-ppc64le -f deployments/Dockerfile.ppc64le .
  
      - name: Build latest-arm64v8
        run: docker build -t ${REPOSITORY}:latest-arm64v8 -f deployments/Dockerfile.arm64 .
  
      - name: Build latest-origin
        run: docker build -t ${REPOSITORY}:latest-origin -f deployments/Dockerfile.openshift .
  
      - name: Tag stable
        run: |
          docker tag ${REPOSITORY}:latest-amd64 ${REPOSITORY}:stable-amd64
          docker tag ${REPOSITORY}:latest-ppc64le ${REPOSITORY}:stable-ppc64le
          docker tag ${REPOSITORY}:latest-arm64v8 ${REPOSITORY}:stable-arm64v8
          docker tag ${REPOSITORY}:latest-amd64 ${REPOSITORY}:${GITHUB_REF##*/}-amd64
          docker tag ${REPOSITORY}:latest-ppc64le ${REPOSITORY}:${GITHUB_REF##*/}-ppc64le
          docker tag ${REPOSITORY}:latest-arm64v8 ${REPOSITORY}:${GITHUB_REF##*/}-arm64v8
  
      - name: Login to registry
        if: github.repository == 'intel/multus-cni'
        run: docker login -u ${REPOSITORY_USER} -p ${{ secrets. REPOSITORY_PASS }}
  
      - name: Push latest/snapshot images
        if: github.repository == 'intel/multus-cni'
        run: |
          docker push ${REPOSITORY}:latest-amd64
          docker push ${REPOSITORY}:latest-ppc64le
          docker push ${REPOSITORY}:latest-arm64v8
          docker push ${REPOSITORY}:stable-amd64
          docker push ${REPOSITORY}:stable-ppc64le
          docker push ${REPOSITORY}:stable-arm64v8
          docker push ${REPOSITORY}:${GITHUB_REF##*/}-amd64
          docker push ${REPOSITORY}:${GITHUB_REF##*/}-ppc64le
          docker push ${REPOSITORY}:${GITHUB_REF##*/}-arm64v8
  
      - name: Create manifest for multi-arch images
        if: github.repository == 'intel/multus-cni'
        run: |
          docker manifest create ${REPOSITORY}:stable ${REPOSITORY}:stable-amd64 ${REPOSITORY}:stable-ppc64le ${REPOSITORY}:stable-arm64v8
          docker manifest annotate ${REPOSITORY}:stable ${REPOSITORY}:stable-amd64 --arch amd64
          docker manifest annotate ${REPOSITORY}:stable ${REPOSITORY}:stable-ppc64le --arch ppc64le
          docker manifest annotate ${REPOSITORY}:stable ${REPOSITORY}:stable-arm64v8 --arch arm64
          docker manifest push ${REPOSITORY}:stable
          docker manifest create ${REPOSITORY}:latest ${REPOSITORY}:latest-amd64 ${REPOSITORY}:latest-ppc64le ${REPOSITORY}:latest-arm64v8
          docker manifest annotate ${REPOSITORY}:latest ${REPOSITORY}:latest-amd64 --arch amd64
          docker manifest annotate ${REPOSITORY}:latest ${REPOSITORY}:latest-ppc64le --arch ppc64le
          docker manifest annotate ${REPOSITORY}:latest ${REPOSITORY}:latest-arm64v8 --arch arm64
          docker manifest push ${REPOSITORY}:latest
          docker manifest create ${REPOSITORY}:${GITHUB_REF##*/} ${REPOSITORY}:${GITHUB_REF##*/}-amd64 ${REPOSITORY}:${GITHUB_REF##*/}-ppc64le ${REPOSITORY}:${GITHUB_REF##*/}-arm64v8
          docker manifest annotate ${REPOSITORY}:${GITHUB_REF##*/} ${REPOSITORY}:${GITHUB_REF##*/}-amd64 --arch amd64
          docker manifest annotate ${REPOSITORY}:${GITHUB_REF##*/} ${REPOSITORY}:${GITHUB_REF##*/}-ppc64le --arch ppc64le
          docker manifest annotate ${REPOSITORY}:${GITHUB_REF##*/} ${REPOSITORY}:${GITHUB_REF##*/}-arm64v8 --arch arm64
          docker manifest push ${REPOSITORY}:${GITHUB_REF##*/}
